[build]
  command = "pnpm build"
  publish = ".next"
  # 指定使用 deploy 分支部署
  base = "/"

[context.production]
  # 生产环境使用 deploy 分支

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
